import JSZip from 'jszip';

export interface GameDataPayload {
  actors: unknown[];
  clips: unknown[];
  sourceName: string;
  files: string[];
}

async function readJson(blob: Blob | undefined): Promise<unknown> {
  if (!blob) return undefined;
  return JSON.parse(await blob.text()) as unknown;
}

function unwrapList(value: unknown, key: string): unknown[] {
  if (Array.isArray(value)) return value;
  if (value && typeof value === 'object') {
    const list = (value as Record<string, unknown>)[key];
    return Array.isArray(list) ? list : [];
  }
  return [];
}

/** Reads the ZIP generated by SWF Forge or a standalone project/actors/clips JSON. */
export async function readGameData(file: File): Promise<GameDataPayload> {
  if (/\.zip$/i.test(file.name)) {
    const zip = await JSZip.loadAsync(file);
    const entries = Object.values(zip.files).filter((entry) => !entry.dir);
    const find = (name: string) => entries.find((entry) => entry.name.toLowerCase().endsWith(`/${name}`) || entry.name.toLowerCase() === name);
    const actorsJson = await readJson(find('actors.json') ? await find('actors.json')!.async('blob') : undefined);
    const clipsJson = await readJson(find('clips.json') ? await find('clips.json')!.async('blob') : undefined);
    const projectJson = await readJson(find('project.json') ? await find('project.json')!.async('blob') : undefined) as { actors?: unknown[]; clips?: unknown[] } | undefined;
    return {
      actors: unwrapList(actorsJson ?? projectJson?.actors, 'actors'),
      clips: unwrapList(clipsJson ?? projectJson?.clips, 'clips'),
      sourceName: file.name,
      files: entries.map((entry) => entry.name),
    };
  }

  const parsed = await readJson(file) as { actors?: unknown[]; clips?: unknown[]; project?: { actors?: unknown[]; clips?: unknown[] } };
  return {
    actors: parsed?.actors ?? parsed?.project?.actors ?? [],
    clips: parsed?.clips ?? parsed?.project?.clips ?? [],
    sourceName: file.name,
    files: [file.name],
  };
}